apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: #{namespace}#-agw-azid
spec:
  type: 0
  ResourceID: /subscriptions/#{subscription_id}#/resourceGroups/#{resource_group_name}#/providers/Microsoft.ManagedIdentity/userAssignedIdentities/#{user_assgined_identity}#
  ClientID: #{user_assgined_identity_clientid}#