apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: #{namespace}#-ingress-azure
  name: #{namespace}#-clusterrole-ingress-controller
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - endpoints
    - pods
    - secrets
    - namespaces
    - services
    - events
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - "appgw.ingress.k8s.io"
    - "networking.istio.io"
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
  resources:
    - ingresses/status
  verbs:
    - update
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch