apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: #{namespace}#-ingress-azure
  name: #{namespace}#-clusterrolebinding-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #{namespace}#-clusterrole-ingress-controller
subjects:
  - kind: ServiceAccount
    name: #{namespace}#-sa-ingress-controller
    namespace: #{namespace}#